[versions]
agp = "8.4.0"
dokka = "1.9.10"
nexusPlugin = "0.25.3"
kotlin = "1.9.23"
kotlinBinaryCompatibility = "0.14.0"
jvmTarget = "11"
androidxComposeBom = "2024.05.00"
androidxComposeCompiler = "1.5.13"
androidxActivity = "1.9.0"
androidxTest = "1.5.2"
androidxCore = "1.13.1"
androidxNavigation = "2.7.7"
photoPicker = "1.0.0-alpha06"
baselineProfiles = "1.3.1"
macroBenchmark = "1.2.4"
uiAutomator = "2.3.0"
spotless = "6.21.0"
junit = "1.1.5"
espresso-core = "3.5.1"
androidxMacroBenchmark = "1.2.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nexus-plugin = { id = "com.vanniktech.maven.publish", version.ref = "nexusPlugin" }
kotlin-binary-compatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinBinaryCompatibility" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
baseline-profile = { id = "androidx.baselineprofile", version.ref = "androidxMacroBenchmark" }

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
photo-picker = { group = "com.google.modernstorage", name = "modernstorage-photopicker", version.ref = "photoPicker" }

# unit test
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTest" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "baselineProfiles" }
androidx-benchmark-macro = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "macroBenchmark" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiAutomator" }
junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }